sudo: required
lenguage: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
env:
  - DJANGO=1.9
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq virtualbox --fix-missing
  - sudo apt-get install -qq vagrant 
install:
  - sudo pip install "pip>8.0.0" wheel
  - sudo pip install "$DJANGO" "coverage=4.0.3"
  - sudo pip install .
branches:
  only:
    - travis-ci
script: coverage run manage.py test manager
after_sucess:
  - coverage report
