sudo: required
language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
env:
  - DJANGO="Django==1.9"
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq virtualbox --fix-missing
  - sudo apt-get install -qq vagrant 
install:
  - sudo -H pip3 install "pip>8.0.0" wheel
  - sudo -H pip3 install "$DJANGO"
  - sudo -H pip3 install -r requeriments.txt
branches:
  only:
    - travis-ci
script: coverage run manage.py test manager
after_sucess:
  - coverage report
